### ISSUE TITLE
Serverless JupyterHub 예제 구현

### ISSUE THREAD

**Issue by chris0765** [StableSpot/StableSpot#10]
https://avishayil.medium.com/serverless-jupyter-hub-with-aws-fargate-and-cdk-2160154187a1

Serverless JupyterHub의 동작 원리를 파악하기 위해 위 예제를 따라서 구현해보는 이슈

**Comment by chris0765** [comment]
혼자서 구현을 시도해보았습니다만, 아무래도 프론트엔드쪽 지식이 부족해 빠르게 진행하기는 어려울듯 합니다.
우선 #7 이슈에서 각 방법마다의 비용 비교를 먼저 진행하고 진행하겠습니다.

**Comment by chris0765** [comment]
프론트를 포함한 전체적인 작업을 @ggamsang 님이랑 진행해보고자 합니다.
@ggamsang 님께서 아직 프로젝트에 대한 추가적인 이해가 필요하므로, 우선 KSC 논문에 집중하여 빠르게 마무리하도록 하겠습니다.

**Comment by ggamsang** [comment]
**프라이빗 url 생성을 위한 route53과 congnito 설정을 위한
congnito를 통한 인증 토큰 획득 방법과 관련 소스코드 공유**

> aws 콘솔에서 congnito user pool 생성
> congnito 콘솔에서 클라이언트 앱 생성
> 웹 앱에서 위의 정보를 이용하여 연결설정 및 실행
> 유저등록
> 발송된인증메일확인
> 로그인
> (F12 > Application > local storage에서 토큰확인할수있음)

- congnito user pool를 생성하고 app client list에서 create app client를 한다 . 
이 과정에서 생성되는 userpool id와 client id를 저장한다. 도메인도 기억해둔다.
- 위의 설정과정 중 인증방법은 otp는 uncheck하고, email만 check한다.

- https://github.com/imMayyur/aws-cognito-with-react 클론하여
- 작업은 4-Session에서 수행한다.
(amplify를 이용하는 방법도 있지만 간단한 리액트앱으로 대체한다.)
.env파일을 생성한 후 
REACT_APP_USERPOOL_ID=유저풀아이디
REACT_APP_APPCLIENT_ID=앱클라이언트아이디
위의 같이 내용을 입력한다.
(node를 설치되고 노드패키지 매니저인 npm도 설치된다,  npm install -g yarn을 통행 yarn을 설치한다.)
yarn ;yarn start

| localhost:3000 |로긴/로긴후페이지|
| localhost:3000/regitster |cognito 유저등록|

todo
- route53에서 CNAME타입 레코드 추가한다. 주소는 유저풀도메인이다.(커스텀 도메인생성으로 원하는 도메인을 설정한다.)
- 위에서 추가된 레코드에 서브도메인(유저아이디.유저풀도메인)으로하는 vpc내 서비스를 연동하는 테스트를 하는 방법에 대해서 알아볼것.
- cognito에서 제공되는 기능들을 더 조사할 필요가 있어보임.
- 로그인을 하면 cognito가 해당url을 전송하는 방법에 대해서 조사해야함.
