### ISSUE TITLE
ALB 대체 가능한 서비스에 대한 조사 

### ISSUE THREAD

**Issue by ggamsang** [StableSpot/StableSpot#12]
본 이슈는 현재 구축 중인 시스템에서 ALB를 대체할 서비스를 연구조사한 결과를 남깁니다.

**Comment by ggamsang** [comment]
현재 시스템에서 alb의 기능은 보안과 라우팅(로드밸런싱)이 주된 기능으로 보이며 이를 nginx를 serverless 혹은 alb보다 적은 리소스를 가지고 운영할 수 있는 방법에 대해서 우선 알아보도록 한다.

**Comment by hyu-leeky** [comment]
Kubernetes 의 서비스를 사용해서 대체가 가능한지 검토.
