### ISSUE TITLE
MemVerge의 jupyter 시스템 탐구

### ISSUE THREAD

**Issue by chris0765** [StableSpot/StableSpot#13]
https://www.mmcloud.io/solutions/jupyter
https://aws.amazon.com/marketplace/pp/prodview-aqmz54rewwebk?sr=0-1&ref_=beagle&applicationId=AWSMPContessa

StableSpot과 유사한 서비스인 MemVerge의 서비스 기능 탐구

* 어떤 기능이 있는지
* 어떤 서비스를 기반으로 작동되는 것 같은지(예: CRIU)

추가로 해당 솔루션과 차이점을 둘 수 있을만한 기능들 탐구

* MemVerge 서비스에서 개선할 수 있을만한 요소들
* MemVerge에는 없는 기능들

**Comment by chris0765** [comment]
서비스 이용 요금으로 0.01$/unit 필요.

서비스 탐색 시 인스턴스의 사용으로 추가 비용이 발생할 수 있음

**Comment by chris0765** [comment]
우선 jaeil@kookmin.ac.kr 계정을 통해 MemVerge 회원으로 가입하였고,
AWS 마켓플레이스에서 Memory Machine Cloud를 subscribe했습니다.

configure를 볼때, 우선 MMC의 경우는 ```완전 서버리스는 아닌 것으로 추측```됩니다.
<img width="257" alt="image" src="https://github.com/StableSpot/StableSpot/assets/66048830/039cb131-0038-434e-b785-959233387dc4">
MMC의 구성 중, MMC software가 t2.medium에서 실행된다고 나와있는 것을 볼 때, 기본적으로 동작하는 메인 서버는 항상 존재해야하는 것 같습니다.

<img width="828" alt="image" src="https://github.com/StableSpot/StableSpot/assets/66048830/0de23f73-e9b3-4b93-b5c7-03c20b9f4b17">

소프트웨어 배포는 CloudFormation으로 진행이 되는 것으로 보입니다.
<img width="1528" alt="image" src="https://github.com/StableSpot/StableSpot/assets/66048830/1675ffc7-f5ba-463b-955f-d526ac2e73f4">
위와 같은 세부 파라미터만 설정해 준 후, 생성을 시작할 수 있습니다.

**Comment by chris0765** [comment]
## MMCloud 요금 정책

<img width="1201" alt="image" src="https://github.com/StableSpot/StableSpot/assets/66048830/66fb5ae7-a38f-4e1a-8904-6a55488671bb">

MMCloud의 라이센스 요금과 같은 경우 다음과 같이 설정되어있습니다.

기본적인 라이센스는 무료이나, Auto-migration을 위해서는 프로 라이센스를 구독하여야 합니다.
프로 라이센스는 Spot 인스턴스를 사용해서 얻는 Savings의 25%를 요금으로 지불합니다.
spot.io와 유사한 요금제 방식으로 보입니다.

## MMCloud 기능 탐구

<img width="1605" alt="image" src="https://github.com/StableSpot/StableSpot/assets/66048830/76d91835-c8d1-46a6-8e5c-b66fb27df320">

MMCloud의 경우 예상했던 대로 기본적인 메인 서버가 존재해야합니다.
OpCenter-MM...이 메인 서버이자 모니터링 서버로, 해당 서버를 이용해 Job들을 실행합니다.

<img width="1907" alt="image" src="https://github.com/StableSpot/StableSpot/assets/66048830/2c322857-b420-4e3e-af21-8e156eb01f57">
서버의 IP를 통해 접속하면, 다음과 같은 기본 화면이 나타납니다. 우측 상단의 메뉴에서 계정을 등록해 라이센스를 인증할 수 있습니다.

<img width="1671" alt="image" src="https://github.com/StableSpot/StableSpot/assets/66048830/dec4c737-6f47-4e52-a0ea-1a687bbf9b5f">
<img width="1672" alt="image" src="https://github.com/StableSpot/StableSpot/assets/66048830/f6f49f13-e564-4e13-ab54-008751d824d8">
Job은 도커 이미지를 사용하며, 기본적으로 빌트인되어있는 이미지들과 Private 탭에서 수동으로 등록 가능한 이미지들이 있습니다.

<img width="1909" alt="image" src="https://github.com/StableSpot/StableSpot/assets/66048830/b2727704-3d04-4694-941e-e37d9c4c5ddd">
Submit Job 버튼을 통해 새로운 Job을 등록할 수 있습니다.

<img width="1193" alt="image" src="https://github.com/StableSpot/StableSpot/assets/66048830/25f57344-2f54-48bc-842f-c316fd0678cd">
https://www.mmcloud.io/get-started/submit-your-first-job
이후 위 링크의 내용대로 Job에 사용할 옵션들을 설정해줍니다.
오른쪽을 볼 때, 'float'라는 명령어를 사용해 컨테이너를 설정하는 것으로 보입니다.

* Image: Job에 사용할 컨테이너 이미지
* Script: 컨테이너 안에서 실행시킬 스크립트
* 인스턴스: CPU, MEM 등의 특정 사양, 혹은 특정 인스턴스 타입
* 볼륨: 스토리지 용량. 이미 존재하는 볼륨 사용, 새로운 볼륨 생성, NFS 마운트 등 가능
* Advanced
  * Policies: 스팟과 온디맨드 사용에 관한 정책. 1) 스팟우선 2) 스팟만 3) 온디맨드만 사용하게끔 설정 가능. Retry Limit, Interval, Price Limit 설정 가능. Auto-Migration 사용 설정 가능(프로 라이센스 필요)
  * Environment Variables: 환경변수 설정 가능
  * Network: Security Group 설정(AWS의 security group id 혹은 GCP의 Network tag), Public IP 할당 설정, Publish Port 설정, 게이트웨이 설정
  * Misc.: Availability Zone 설정, Container Shared Memory Size 설정, Periodic Snapshot 설정, Job Duration Limit 설정, (CPU, MEM으로 인스턴스 타입 결정 시)특정 인스턴스 타입을 제외하고 사용 가능, 커스텀 태그 설정


<img width="1663" alt="image" src="https://github.com/StableSpot/StableSpot/assets/66048830/a14a1385-76cb-4aae-8781-604838c96404">
모든 설정 완료 후 Submit 하면 위의 사진처럼 Job들의 ID, Name, Host, User, Status, Submitted Time, Duration, Cost, Action 확인 가능하고, ID 클릭 시 해당 Job의 세부 내역을 확인할 수 있습니다.

시스템 구성을 확인해 봤을 때, MMCloud는 이전 Skypilot처럼 배치 단위의 작업을 실행하는데 적합한 형태로 보이고, 여기에 Jupyter와 같은 일반 워크로드들도 사용할 수 있는 것으로 보입니다.

그런데 Jupyter Job을 실행시키고자 여러 차례 시도를 하고 있는데, 잘 접속되지 않는 듯 합니다.
이 부분은 계속 시도해보겠습니다.

**Comment by chris0765** [comment]
https://github.com/MemVerge/nf-float/blob/master/plugins/nf-float/src/main/com/memverge/nextflow/FloatTaskHandler.groovy

https://docs.memverge.com/mmce/current/userguide/olh/oxy_ex-1/topics/mmce_bondi_migrate.html

float 명령어와 관련된 MemVerge의 github을 발견했습니다.
간단하게 살펴보았을 때, float 명령어 전체가 담긴 코드는 아니고, nextflow에서 float 명령어를 설치하기 위한 repo로 보입니다.
결국 전체 코드를 확인해보기 위해서는 직접 설치하여 확인해보기는 해야할 것 같습니다.

document만 살펴봤을 때, migration 과정은 (체크포인트 파일 생성) -> (파일 이용하여 리스토어)로 보입니다.
<img width="1117" alt="image" src="https://github.com/StableSpot/StableSpot/assets/66048830/d3a913e3-d378-4b6d-9ba3-87f0f372377a">
다만 이것이 CRIU를 이용하는 것인지는 아직 확실치 않아 코드를 살펴보도록 하겠습니다.

**Comment by chris0765** [comment]
우선 CloudFormation으로 생성된 메인 서버에 ssh로 접속해 `whereis float` 명령어로 위치를 파악해보았습니다.

/opt/memverge/bin/float 파일로 존재하며, 내용물은 아래와 같습니다.
아래 내용이 전체는 아니고, 하단에 이와 유사한 형태로 더 많은 분량이 존재합니다.
<img width="565" alt="image" src="https://github.com/StableSpot/StableSpot/assets/66048830/5c62fe8b-a8f9-4baa-8a56-86b2024ebe0d">

내용물을 확인해보았을 때, 명령어가 동작되는 코드는 암호화가 되어있습니다.
코드를 직접 분석하는 것은 불가능합니다.

대신에 진행해볼 계획은 다음과 같습니다.
* JupyterNotebook 컨테이너를 실행. 접속 가능 확인.
* FIS를 통해 모의 인터럽트 마이그레이션을 수행할 수 있을지 확인. 불가능하다면 프로 라이센스 구독 후 메모리 사용량을 높여서 마이그레이션 시도
* 마이그레이션의 경우 체크포인트 파일이 생성되므로, 이를 중간에 확인할 수 있는지 체크. 확인 가능하다면 criu에 의해 복원이 가능한지 체크.
* documentation을 통해 세부 기능 파악

**Comment by hyu-leeky** [comment]
재일아. 암호화는 아니고. binary 파일로 만들어져 있다고 보는게 맞겠지. 해당 파일말고 다른 관련된 라이브러리 및 코드 등이 있는지 조금 더 검색해보고 다른 방법으로 분석할지 정하자.

**Comment by chris0765** [comment]
nf-float github을 참고하여 nextflow 설치 -> nf-float 플러그인 추가 작업을 진행한 후, 찾아볼 수 있는 코드 파일이 존재하는지 확인해보겠습니다.

이와는 별개로 주피터 노트북을 실행할 때 도움이 될만한 github example을 발견했습니다.
https://github.com/Quansight/memverge-jupyter/tree/main/MMCloud
우선 그대로 시도해봤을 때는 정상적으로 작동하지는 않았지만, 여러 부분들을 변경해가며 시도하기에 어느정도 실마리가 되지 않을까 싶습니다.

**Comment by hyu-leeky** [comment]
오케이. 재일아 다양한 소스로 부터 많은 부분을 시도해보자.

**Comment by chris0765** [comment]
## MemVerge의 Memory Machine Cloud 마이그레이션 방식 분석

MMCloud에서 마이그레이션을 수행하는 방법을 탐색하였습니다.

1. float 커맨드 탐색

MMCloud에서 마이그레이션을 비롯한 모든 작업을 총망라하는 커맨드인 float의 세부 코드를 분석하고자 시도했습니다.
CloudFormation으로 생성된 MMCloud 메인 서버의 float 커맨드 파일은 바이너리 파일로 코드를 읽어볼 수 없게 되어있었으며,

https://github.com/MemVerge/nf-float/tree/master
위 링크의 내용대로 nextflow에서 plugin을 추가해보았지만, 이는 커맨드를 설치하는 과정이 아니라, nextflow에서 float를 사용할 수 있게 해주는 것으로, 실제 코드는 nextflow의 서버에 있어, 커맨드 실행 시마다 네트워크를 통해 명령어를 가져오는 것으로 보입니다.

결과적으로 float 커맨드의 코드를 직접 분석하는 것은 불가능했습니다.

2. 관련 문서 탐색

마이그레이션 과정 관련하여 발표된 논문이나 인터넷 기사가 존재하지 않을까 하여 MemVerge와 관련된 내용들을 살펴봤습니다.
https://docs.memverge.com/mmce/2.2/releasenotes/pdf/mmce_2_2_releasenotes.pdf
https://docs.memverge.com/topics/mmce.html
공식 docs pdf나 사이트에는 자세한 방식 관련 내용이 보이지는 않았습니다.

대신 arxiv에 발표된 논문에서 결과를 얻을 수 있었습니다.
https://arxiv.org/abs/2210.02589
https://docs.google.com/presentation/d/1XAh3_K7WOaKDOln0gdNFokIG1PMhBJe7Z4ZpoKFtB3I/edit?usp=sharing

제가 예전에 세미나에서 발표하기도 했었던 논문인데, 해당 논문의 발표 저자가 MemVerge Inc.임을 확인할 수 있습니다.
논문의 내용을 살펴보다보면, 시스템이 체크포인트를 위해 CRIU를 사용했다는 내용을 확인할 수 있습니다.
<img width="345" alt="image" src="https://github.com/StableSpot/StableSpot/assets/66048830/b2993d83-a2f0-44e6-95ae-e3a8fef2c61e">

결론적으로 MMCloud의 마이그레이션 시스템은, 스케쥴러를 통해 주기적으로 CRIU를 이용한 체크포인팅을 진행합니다. 별도의 특별한 처리는 들어있지 않습니다.

**Comment by hyu-leeky** [comment]
오케이. 논문을 발표했다면 아무래도 해당 내용을 실제로 구현했을 가능성이 크기는 하겠다. 논문이 논문 트래킹 이슈에 포함 안되어 있다면 추가해두자.

**Comment by chris0765** [comment]
Jupyter Notebook 실행을 계속 시도해보고 있는데, 계속 실패하고 있습니다.

이 이상 시도해봤자 성공할 수 있을지 장담하기가 어려울 것 같아 하루 정도만 더 시도해보고,
1) 성공한다면 MMCloud의 실제 마이그레이션 경험이 어떤지 알아보고,
2) 실패한다면 MMCloud의 기능 자체는 문서를 통해 파악했으므로, 발전시킬 수 있는 요소를 찾아보고 StableSpot에 반영하도록 하여 시스템 구조 설계를 진행하겠습니다.

**Comment by hyu-leeky** [comment]
그래 그렇게 하자. 추가적으로 지속적으로 에러가 발생하면 서비스 제공업체에 물어볼수도 있으니 그런 방향도 고려해보도록 하고.

**Comment by chris0765** [comment]
<img width="1188" alt="image" src="https://github.com/StableSpot/StableSpot/assets/66048830/0fc1421d-d130-4aa7-bcc7-45bbb583a03d">

MMCloud에서 주피터 노트북을 실행하는데 성공했습니다.
User Script쪽에 문제가 있었을것이라 생각했는데, Security Group쪽에 문제가 있었습니다.

주피터 노트북 실행까지 성공했으니, 프로 라이센스 구독 후 마이그레이션 작업 살펴보도록 하겠습니다.

**Comment by chris0765** [comment]
말씀하신것처럼 마이그레이션이 CRIU로 동작하는걸 확인한 지금, 굳이 프로 라이센스를 구독해서 마이그레이션을 시도해볼 필요는 없을 듯 합니다.

처음 직접 마이그레이션을 시도해보고자 한 이유는, float 코드를 직접 확인하는 것이 불가능해, 마이그레이션 과정에서 생성되는 파일과 로그를 분석하여 CRIU와 같은 방식으로 동작하는지 확인하고자 했던 것인 만큼, 더이상 진행할 필요는 없을 것 같습니다.

StableSpot 시스템 구성 쪽으로 집중해보도록 하겠습니다.

**Comment by hyu-leeky** [comment]
"마이그레이션 과정에서 생성되는 파일과 로그를 분석" -> 파일과 로그를 접근 할 수 없을것 같다고 판단을 한 건지?

**Comment by chris0765** [comment]
파일과 로그를 분석해 마이그레이션이 CRIU를 사용하는지, 아니면 다른 툴을 사용하는지 파악하고자 하였는데,
MemVerge에서 작성한 논문을 통해 따로 파일을 분석하지 않아도 CRIU를 사용하고 있음을 알 수 있었으므로 굳이 실제로 마이그레이션을 수행해볼 필요가 없을 것이라 판단했습니다.

교수님이 오늘 말씀해주신것처럼 "마이그레이션이 잘 되더라" 정도의 결론밖에는 얻을 게 없을 것 같습니다.

**Comment by hyu-leeky** [comment]
다시 생각해보면 전에 준호가 실험했을때 무한 반복문을 돌리면서 마이그레이션 시 예상치 못한 에러 메시지가 나오기도 하고 했던것 같은데. 그리고 로그 같은걸 발견하면 criu 의 어떤 명령어 및 옵션을 사용하는지 알 수 있을것 같기도 해.

**Comment by chris0765** [comment]
넵 그러면 마이그레이션은 한번 진행해 보겠습니다.

**Comment by hyu-leeky** [comment]
진행할때 내부적으로 생성되는 로그나 파일등을 같이 파악해 볼수 있는 방향으로 진행하자. 오후에 이야기했던건 단순히 기능이 동작하는지 여부만 테스트 하는건 피하는게 좋겠다는 생각이었으니.

**Comment by chris0765** [comment]
<img width="1568" alt="image" src="https://github.com/StableSpot/StableSpot/assets/66048830/e9c9c035-5e39-4a35-8bdc-860dff27bb13">

우선 이번 KSC에 작성한 논문처럼 NFS를 사용해 메모리 데이터와 파일 데이터를 분리하여 관리하지는 않습니다.
주피터 노트북 컨테이너 내에 약 6GB 정도의 SpotLake 데이터를 업로드 하였을 때, 위 사진처럼 EFS는 230MB를 유지하고 있습니다.

실제로 CRIU를 사용하여 전체 컨테이너를 체크포인트 했을 때의 시간과 비교하면 별 차이가 없음을 확인할 수 있습니다.

<img width="1887" alt="image" src="https://github.com/StableSpot/StableSpot/assets/66048830/e03fb937-2300-4f9a-ab2c-578ba59c2836">

EBS 볼륨 할당을 생각하지 못해 약 14% 적은 row가 업로드되었음을 생각하면 4초 정도의 차이는 무시할 수 있는 수준입니다.

로그를 살펴본 결과 마이그레이션 절차는 아래와 같습니다.
1. 새로운 인스턴스 요청
2. 체크포인팅
3. 기존 인스턴스에서 EBS Detach
4. 새로운 인스턴스에서 EBS Attach
5. 리스토어
6. 기존 인스턴스 종료

**Comment by hyu-leeky** [comment]
오케이. 실험 결과에 기반해서 그렇게 판단을 내렸구나. 혹시 EC2 쉘어 접근 가능하다면 정말로 EBS 가 그대로 유지되는지 확인 가능할까? EFS 사용은 반드시 해야 하는건가? 어떤 계기로 EFS 를 사용하게 되는거야?

**Comment by chris0765** [comment]
# MemVerge의 Memory Machine Cloud 분석 내용 정리

## 기능 분석

* 스팟 인스턴스에서 batch 작업 수행 가능
* 스팟 인스턴스에서 endless 작업 수행 가능
* 마이그레이션 기능
  * CPU Usage가 사용자가 설정한 수치 이하라면 인스턴스 자동 다운그레이드
  * CPU Usage가 사용자가 설정한 수치 이상이라면 인스턴스 자동 업그레이드
  * Memory도 마찬가지로 AutoScale 가능
  * 특정 인스턴스 타입을 지정하거나, CPU와 Memory의 Min-Max 사이즈를 설정하여 수동 마이그레이션 가능
* Cost Savings 시각화
* Job마다 발생한 비용 비교 가능

## 마이그레이션 분석

* Redhat OS 기반
* 컨테이너 도구로 Podman 사용
* CRIU 사용
* 메모리 데이터만 체크포인트
  * EBS 마운트 볼륨을 Podman의 루트 경로로 지정
  * -e 옵션을 사용하지 않아 자동으로 EBS에 체크포인트 파일 작성됨
* EBS를 기존 인스턴스에서 detach하고, 신규 인스턴스에 attach하여 restore 수행
