### ISSUE TITLE
인스턴스 보안 접속을 위한 Cognito 시스템 구축

### ISSUE THREAD

**Issue by chris0765** [StableSpot/StableSpot#14]
Route53을 통해 일관된 URL을 제공하는 스팟 인스턴스 시스템을 Cognito를 통해 인증된 사용자만이 접속할 수 있게끔 시스템을 구축할 수 있는지 테스트.

[세부 개요]

1. 로그인 페이지는 S3나 Amplify를 통해 호스팅되는 정적 웹 페이지에서 동작
2. 로그인이 성공하면 스팟 인스턴스에서 동작중인 웹서버에 접속 가능한 버튼이 있는 페이지로 이동
3. 기존의 로그인 데이터를 통해서 웹서버에 접속할 수 있도록 환경을 구성할 수 있는지 파악

본 이슈는 완전 서버리스 구조에서 일관된 URL 제공 & 인스턴스 보안 접속이 가능한지 알아보기 위한 이슈로, 불가능하다면 완전 서버리스를 포기하고 메인 서버를 하나 두는 것이 어떨까에 대한 논의가 필요.

**Comment by chris0765** [comment]
https://velog.io/@moey920/AWS-EKS-Cognito-Route53-ACM-VPC-EC2%EB%A5%BC-%ED%99%9C%EC%9A%A9%ED%95%98%EC%97%AC-KUBEFLOW%EB%A5%BC-%EA%B5%AC%EC%B6%95%ED%95%B4%EB%B3%B4%EC%9E%90

위 블로그의 글은 Cognito에 Route53 도메인을 사용함.
위 예제를 따라서 작성해보고, 의도대로 Cognito 인증을 통해서만 Route53 도메인에 접근할 수 있다면 예제와 같은 시스템을 StableSpot에 적용

**Comment by hyu-leeky** [comment]
재일아. 이부분은 김정혁 연구원님 한테 전달해서 보는것도 좋을것 같아. @ggamsang

**Comment by ggamsang** [comment]
제가 수행한 것을 상기해보며, 본 이유에 대해서 혹시나 도움이 될까 남깁니다.

유저는 웹브라우저를 통해 aws cognito인증과정을 거쳐, 웹브라우저가 지정된 저장소에 인증토큰을 저장합니다. 도메인을 기준으로)
