### ISSUE TITLE
Multi-Region에서 EFS/EBS를 사용한 데이터 공유

### ISSUE THREAD

**Issue by chris0765** [StableSpot/StableSpot#15]
기존 MemVerge의 MMCloud의 한계로는 단일 Region에서만 동작한다.
이는 구현과 관리에는 편리하나, 타 Region의 더 안정적이고 저렴한 인스턴스를 사용할 수 있는 기회를 포기해야 한다는 한계점이 될 수 있다.

이를 해결하고 개선된 시스템을 개발하기 위한 방법을 연구한다.

**Comment by chris0765** [comment]
## 이슈를 해결하기 위한 방법 탐구

1. AWS Datasync 사용

https://aws.amazon.com/ko/datasync/
![image](https://github.com/StableSpot/StableSpot/assets/66048830/4d50c88a-1da6-4303-a1cb-ed889c2133e1)

AWS 데이터싱크를 사용하면 EFS에서 EFS로의 데이터 전송이 가능함.
해당 서비스를 사용해 편리하게 데이터를 타 리전으로 전송할 수 있음.

다만 데이터 전송 시 GB당 0.0125USD의 요금이 부과됨(Oregon 기준)

2. EFS Util 사용

https://docs.aws.amazon.com/efs/latest/ug/mount-different-region.html

AWS Documentation에서는 EFS를 다른 AWS Region에 마운팅하기 위한 방법을 제안해주고 있음.
efs-utils.conf 내의 region 값을 EFS가 위치하는 Region과 동일하게 변경해주는 것으로 시스템을 우회할 수 있음.

3. 데이터 전송 기능 직접 구현

DataSync보다 저렴한 가격에 타 Region으로 데이터 전송이 가능함.
구현의 난이도가 높음.

## 계획

우선 1, 2번을 수행해보고, 동일 Region 내에서 마이그레이션이 수행될 때와의 마이그레이션 시간 차이를 분석한다.

**Comment by hyu-leeky** [comment]
재일아. 생각을 잘 해볼께. 우리가 연구를 하는건데 이렇게 해서 서비스를 사용해서 성능을 개선하는게 연구로서 큰 의미가 있을것 같지는 않아. 그런 부분도 함께 고민해볼래? 어떤 내용인지 이해가 어렵다면 이야기를 나눠보고.

**Comment by chris0765** [comment]
넵, 어떤 말씀인지 이해됩니다.

말씀해주신대로 이런 부분은 판매하는 솔루션으로써는 의미가 있을 수 있지만,
연구하고 논문을 작성해야 하는 입장에서는 주가 아닌 부가적인 요소가 될 것 같습니다.

우선 Checkpoint 성능 개선과 함께 마이그레이션 시간 단축을 위한 방법을 중점적으로 고민해보겠습니다.

**Comment by chris0765** [comment]
이 이슈에 대해서도 잠시 생각해봤는데,

단순히 "여러 리전을 사용할 수 있다."에서 그치는 것이 아니라, "타 리전의 더 저렴한 스팟 인스턴스를 사용하는 것으로 기존 시스템과 비교하여 OO%의 비용 절감을 얻을 수 있으며, 이에 반해 물리적 거리에 따른 성능 저하는 OO%에서 그쳤다." 정도로 논문에 사용할 수는 있을 것 같습니다.

다만 위에서 이야기한대로, 리전에 따른 Spot Price의 차이는 Ondemand와 비교한 Savings에 비해 그리 크지 않아 주된 연구 내용으로는 어렵고,
마이그레이션 시간 단축 연구가 완료된 후에 내용에 추가할 수는 있을 것 같습니다.

**Comment by hyu-leeky** [comment]
응 재일아. "이에 반해 물리적 거리에 따른 성능 저하는 OO%에서 그쳤다" 에서 기존의 클라우드 서비스 사용시에는 100 초였는데, 우리가 제안한 방법으로 하면 50초가 걸렸다. 이런식의 서술이 나오는 결과물이어야 할것 같아.
그리고 여러 region 에서 spot instance 구동하면 savings 차이는 크지 않을수 있는데, sps 감안한 안정성까지 고려하면 차이가 클 수 있거든. 네spot instance 에서 multi-region deployment 개념을 도입하는 방안으로 접근해보면 좋을것 같아.

그리고 이 이슈는 연구에 가까우니 이제 research-issue 에 만들어서 트래킹 하자.
