### ISSUE TITLE
Cognito를 이용한 로그인 시스템 구축

### ISSUE THREAD

**Issue by jhM00n** [StableSpot/StableSpot#19]
테라폼을 통해 리소스 생성시마다 변경되는 url에 대한 일관성을 유지해야하는 문제가 존재, 따라서 ssm parameter store에 cognito user pool id와 client id를 저장함. 

이후 ssm parameter store에서 조회하여 로그인 기능을 구현하는 이슈

**Comment by jhM00n** [comment]
1차적으로 cognito를 이용한 로그인 기능 구현했습니다.

구조는 다음과 같습니다.
1. 로그인 페이지에서 username과 password를 입력
2. aws sdk로 입력 받은 username과 password를 람다로 전송
3. 람다에선 다음과 같은 역할을 함.
  - cognito user pool의 client app과 연동하기 위해 필요한 secret hash 생성
  - cognito 생성 시 ssm parameter store에 저장한 user pool id와 client id를 조회
  - 이후 응답 받은 username과 password, user pool id, client id, secret hash와 함께 로그인 시도
4. 로그인 완료 후 /main으로 리디렉션

위와 같이 구현 후 등록된 유저만 로그인이 되는 것을 확인했습니다.
일단은 cognito를 사용해서 로그인만 하도록 구현 했으므로, JWT 토큰을 사용하여 로그인을 하도록 변경 후 업데이트 하겠습니다.

**Comment by hyu-leeky** [comment]
cognito 를 사용해서 로그인 인증 기능이 구현된거지? JWT 를 이용해서 로그인 세션 정보 유지는 필요한거고?
가능하면 보여줄 수 있는 데모 사이트는 있으면 좋겠다. 진행 상황 및 필요 작업 파악 할겸 해서.

**Comment by jhM00n** [comment]
네, cognito를 사용한 로그인 기능은 구현되었습니다. 
테스트는 로컬에서 진행해 데모 사이트가 아직 없으나, JWT를 사용해 로그인 세션 정보 유지까지만 업데이트하고 바로 데모 사이트 만들어서 진행 상황 보실 수 있도록 하겠습니다.

**Comment by jhM00n** [comment]
jwt 토큰을 사용한 로그인 및 세션 유지 구현 완료했습니다.

## lambda
https://github.com/StableSpot/StableSpot/pull/20
### 구조
- 로그인 페이지에서 username과 password를 입력하고, aws sdk로 입력 받은 username과 password를 람다로 전송
- 람다에서 하는 일
1. cognito user pool의 client app과 연동하기 위해 필요한 secret hash 생성
2. cognito 생성 시 ssm parameter store에 저장한 user pool id와 client id를 조회
3. 이후 응답 받은 username과 password, user pool id, client id, secret hash와 함께 로그인 시도
4. cognito의 jwks url에서 key set 가져오기
5. id token 검증
6. 공개키 찾기
7. 서명 검증
8. 로그인 성공시 id token과 access token 응답

### 함수
- get_ssm_parameter: 함수는 ssm parameter store에 저장된 값을 불러옴.
- get_secret_hash: cognito는 사용자가 로그인을 시도하면, 입력한 비밀번호를 hash화하여 cognito에 저장된 hash와 비교를 시도함. 따라서 hash화 해야지만 cognito를 사용할 수가 있는데 이를 위해 hash화하는 함수임.


## front
https://github.com/StableSpot/StableHubWeb/pull/2

### 진행한 작업
- 로그인 기능을 가진 lambda에 username(email), password 전달
- lambda에서 로그인에 성공하면 jwt token을 받아 쿠키에 저장 후 /main으로 리디렉션
- 로그아웃 기능 추가(쿠키에 저장한 jwt token 삭제)
- token을 가지고 /login 페이지로 접근시 자동으로 /main 페이지로 리디렉션
- jwt token의 수명을 넘어서면 /login으로 리디렉션
- jwt token의 수명은 cognito에서 설정해야함.


코드 리뷰 후 데모 사이트 만들겠습니다.

**Comment by hyu-leeky** [comment]
오케이 지훈아 수고했다. 목요일 이후로 시간내서 한번 설명 부탁한다.

**Comment by jhM00n** [comment]
데모 사이트를 만들기 위해 프론트를 빌드하는 도중 아래와 같은 에러가 발생해 빌드가 안되고 있습니다. 해결 후 다시 진행하겠습니다.

```
   Linting and checking validity of types  . ⨯ ESLint: Failed to load config "next/babel" to extend from. Referenced from: /Users/jihun/Desktop/ddps/StableHubWeb/.eslintrc.json
```

```
   Generating static pages (0/7)  [    ]ReferenceError: location is not defined
```

**Comment by jhM00n** [comment]
css와 image가 깨지는 현상을 지홍님께 여쭤보아 시도해보았으나, 여전히 아래 이미지와 같이 해결되지 않았습니다.
더 찾아보고 해결해보도록 하겠습니다.
![image](https://github.com/StableSpot/StableSpot/assets/90144123/878a155a-b244-4201-9539-f01a72359494)

지홍님께서 알려주신 해결책은 next.config.json을 아래와 같이 수정하는 것이었습니다.
```
// next.config.json
/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  images: {
    unoptimized: true,
  },
  output: "export",
};

module.exports = nextConfig;
```

**Comment by hyu-leeky** [comment]
일반적인 웹 프로그래밍 관점에서 디버깅을 해야겠구나. 시작을 했으니 조금 더 깊이 있게 봐서 해결을 해보자.

**Comment by jhM00n** [comment]
데모 사이트를 만들었습니다. 로그인 및 세션 유지 기능이 정상작동함을 확인하였고, url은 https://notebook.ddps.cloud/ 입니다.

## 변경사항

### 프론트

- aws sdk를 사용하여 lambda를 직접 호출하는 부분을 lambda function url을 사용하여 호출하도록 변경

## 문제해결사항

### build된 html 파일의 image와 css가 깨지는 현상

→ html 파일의 css와 image가 루트경로(/)로 시작하여 로컬환경에서 비정상작동함. 그러나 웹페이지를 s3 버킷으로 호스팅할때는 루트 경로를 사용하기 때문에 정상작동함.

### 웹페이지를 s3에 호스팅 후 문제점

url(notebook.ddps.cloud)로 접근할때는 괜찮으나, 새로고침 시 아래 이미지와 같이 정상접근이 되지 않음.

![image](https://github.com/StableSpot/StableSpot/assets/90144123/ec49b203-5a50-499f-9cbb-a4d32e63e649)
해결방법

CloudFront에서 http 오류코드 404, 403의 응답 페이지 경로로 /index.html를 설정

**Comment by hyu-leeky** [comment]
오케이. 드디어 올렸구나 ㅎㅎ 고생했다.

경로를 못찾는 문제는 S3 를 사용하면서 해결이 된듯 하고.

새로고침시 에러가 나는건 이상한데, 404 를 index.html 로 리디렉트 하면 되는걸보면 뭔가 경로 설정의 문제 같아 보이기는 한다.

일단 계속 추가적인 기능을 구현해 나가자. landing 페이지에서 실제로 노트북 구동 환경 포함해서.

**Comment by jhM00n** [comment]
완료했으므로 issue close.
