### ISSUE TITLE
서버 생성 기능 구현

### ISSUE THREAD

**Issue by jhM00n** [StableSpot/StableSpot#24]
Create Server 진행시 server가 생성되도록 하는 이슈

**Comment by jhM00n** [comment]
현재 진행상황입니다.

create server로 spot 생성 요청을 보낸 후, spot instance가 생성되고, DB에 등록하는 것까지 확인했습니다.

create 요청시 진행 로직
1. 인스턴스 타입 선택
   - 인스턴스 타입 직접 선택
   - 또는 cpu, memory, gpu의 min, max 값 입력하기
3. 인스턴스 생성을 위해 vpc, subnet id 가져오기
4. security group 생성
    - ssh, web_suppport,  user port
5. 인스턴스 타입이 지원하는 아키텍쳐 확인
    - x86과 arm 모두 지원 시 x86을 우선으로 선택
    - 선택한 아키텍쳐에 맞춰 ami 설정
6. ami, 인스턴스 타입, security group 등으로 spot instance 요청
    - public ip를 무조건 설정해야하는지에 대한 고민?
    - ami는 redhat 9.0 사용
7. instance id 및 ip address 가져오기
8. 생성된 인스턴스를 인스턴스 관리 DB에 등록
---
현재 진행되지 않은 부분
- 생성된 인스턴스의 CPU, MEM Usage를 체크하는 EventBridge Alarm, Rule을 생성 후 Migrator에 연결
- 웹페이지(web_support)를 지원한다면 ALB에 연결

**Comment by hyu-leeky** [comment]
오케이. 뭔가 진도가 조금 나갔구나. 진행상황 같이 한번 보면 좋겠다. 다음주 월요일에 간단히 한번 보자.

**Comment by jhM00n** [comment]
create sever 기능은 유저가 입력한 정보를 바탕으로 알맞은 인스턴스 타입을 선택하여 스팟 인스턴스를 생성합니다.
이후 입력 받은 이미지로 podman을 사용하여 컨테이너를 실행하고, 유저가 원한다면 컨테이너에 대한 웹서비스 연결까지 지원합니다.

---
### server create console
![image](https://github.com/StableSpot/StableSpot/assets/90144123/719d4eb6-67b0-427e-a5af-8606165d7fc4)
![image](https://github.com/StableSpot/StableSpot/assets/90144123/dcfb8678-2ac2-4060-ba15-538e60a2f2d8)
1. Server Name
  - 생성할 서버(인스턴스) 이름
2. Server Configure
  - Docker Image
    - 사용자가 사용하려는 도커 이미지
    - ex) docker.io/jupyter/base-notebook 이미지를 입력 시 서버 생성 후 `podman run`으로 해당 이미지를 사용하는 컨테이너 실행
  - Specify Size
    - CPU, MEM, GPU MEM의 최소 및 최대 값을 입력하여 인스턴스 타입 추천 알고리즘으로 인스턴스 타입을 선정
  - Specify Type
    - 단순히 사용자가 사용하려는 인스턴스 타입 입력
      - ex) t3.small 
  - Auto-migration by CPU usage
    - CPU 사용량이 일정치를 넘어가면 더 높은 사양의 인스턴스로 migration
  - Auto-migration by MEM usage
    - MEM 사용량이 일정치를 넘어가면 더 높은 사양의 인스턴스로 migration
  - User data
    - 일반적으로 의미하는 instance type 등의 userdata가 아닌 인스턴스 내에 컨테이너가 시작될 때 자동으로 실행할 추가 명령어의 집합을 의미
    - 컨테이너의 환경을 설정하거나 애플리케이션을 초기화하는 등의 작업을 수행할 수 있음.
    - ex) jupyter 이미지를 입력한 유저가 userdata에 다음과 같이 입력한다면
      - `start-notebook.sh --NotebookApp.password='' --NotebookApp.token='' --NotebookNotary.db_file=':memory:'`
    - 컨테이너 시작 명령어가 다음과 같이 됨.
      - `sudo podman run --name jupyter -e GRANT_SUDO=yes --user root -p 8888:8888 -d jupyter/base-notebook start-notebook.sh --NotebookApp.password='' --NotebookApp.token='' --NotebookNotary.db_file=':memory:'
` 
3. Security Configure
  - Port
    - 컨테이너 실행할 때의 port
  - SSH Connection
    - ssh port 22 설정
  - Web Connection
    - 웹 서비스 연결에 사용할 port

**Comment by hyu-leeky** [comment]
현재 notebook 컨테이너를 수행하는 기능이 구현 되었다는 이야기?

**Comment by jhM00n** [comment]
> 현재 notebook 컨테이너를 수행하는 기능이 구현 되었다는 이야기?

ssh 접속을 위한 key-pair 설정이 진행되지 않아 인스턴스 접속이 불가능해 아직 확인하지 못했습니다.
확인 후 다시 이슈 업데이트 하겠습니다.

**Comment by jhM00n** [comment]
현재 확인결과 podman run으로 notebook 컨테이너를 실행하는 것을 확인했습니다. 그러나 userdata 전달 과정의 문제로 인해 notebook 컨테이너에 접근이 불가능해 해결 후 업데이트 하겠습니다.

**Comment by jhM00n** [comment]
현재 진행 상황입니다.

화요일 미팅에서 보여드린 것처럼 서버 생성 후 Connect를 클릭해 입력한 컨테이너 이미지의 웹서비스를 이용할 수 있습니다. notebook 컨테이너에서 간단한 워크로드를 돌렸을 때, 정상작동함을 확인했습니다.
![image](https://github.com/StableSpot/StableSpot/assets/90144123/e42e16f4-bfca-421c-b8a1-65342116de6a)
![image](https://github.com/StableSpot/StableSpot/assets/90144123/0c2e64ba-813d-4223-b752-234bc07e7c71)
```
num = 0
for i in range(1001):
    num = num + 1

print(num)
```
아직 connect 버튼을 눌렀을 때만 접근이 가능하도록 하는 부분은 미구현 상태입니다(브라우저에 엔드포인트를 입력했을 때 접근이 가능함). 이 부분은 인스턴스의 userdata에서 efs 설치 시 에러가 발생해 수정 후 진행하도록 하겠습니다.

**Comment by hyu-leeky** [comment]
efs 사용하는 방안에 대해서 업데이트 해주고, 굳이 필요하지 않다면 추가하지 말자.
일단 동작하는걸 보니 괜찮아 보이기는 한다. sagemaker 의 spot 기반 Notebook 과 차이점에 대해서도 함께 분석해보자.

**Comment by jhM00n** [comment]
EFS를 사용하는 이유는 다음과 같습니다.

기존 시나리오에서는 checkpoint 파일을 tar.gz로 압축한 후, scp를 통해 전송하고 압축을 해제하여 restore을 진행합니다. 그러나 EFS를 사용할 경우, EFS에 직접 checkpoint를 저장하고 restore 할 수 있습니다. EFS를 사용하면 압축, 전송, 압축 해제 과정이 없어져 이러한 과정에서 발생하는 시간이 줄어들어 EFS를 사용하기로 했습니다.

**Comment by hyu-leeky** [comment]
오케이. 그런 측면이 있겠구나. 아직은 완전한 서비스를 구성하는건 아니니, 지금 단계에서 굳이 efs 를 연결할 필요는 없을것 같아.
efs 과금 메커니즘을 한번 봐볼래? 그냥 만들어만 둬도 과금이 되는지? 데이터 저장없이

**Comment by jhM00n** [comment]
efs를 생성만 하고, 저장한 데이터가 없는 경우에는 과금이 되지 않는다고 합니다.
사용한 기본 및 백업 스토리지와 EFS 파일 시스템에 대한 읽기, 쓰기, 계층화 작업에 대한 비용만 청구된다고 되어 있습니다.

**Comment by jhM00n** [comment]
기본적인 서버생성은 완료.
efs와 alb는 각각 마이그레이션과 alb 이슈에서 진행하므로 issue close.
