### ISSUE TITLE
JupyterHub 동작 방식 파악

### ISSUE THREAD

**Issue by chris0765** [StableSpot/StableSpot#4]
JupyterHub가 JupyterNotebook과 어떤 부분이 다르게 동작하는지, 어떤 특징이 있는지 등을 파악한 후,
StableSpot 시스템에 어떻게 적용할 수 있을지를 분석

**Comment by chris0765** [comment]
JupyterHub를 실제로 설치해서 사용해봤습니다.
<img width="1916" alt="image" src="https://github.com/StableSpot/StableSpot/assets/66048830/1fab91cf-6035-4d8b-a7ff-850ba7693687">

프론트 부분에서 Spawner가 어떤 식으로 동작하는지는 확인하기 어려워, github의 코드를 확인해봐야 할 듯 합니다.

**Comment by hyu-leeky** [comment]
오케이 그렇게 하자. Kubernetes 기반으로 동작한다고 하니 k8s 명령어를 호스트에서 바로 실행해보면 알것 같기도 하고. 다양한 방법으로 분석을 진행해보자.

**Comment by chris0765** [comment]
https://github.com/jupyterhub/jupyterhub/blob/main/jupyterhub/spawner.py

spawner.py만 해도 약 1800줄의 코드로 이루어져 있어, 정확히 파악하는데 시간이 조금 걸릴 것 같습니다.

**Comment by chris0765** [comment]
spawner가 kubernetes 하나만 있는 것이 아니고, 여러 종류의 커스텀 spawner가 존재하는 듯 합니다.
<img width="1110" alt="image" src="https://github.com/StableSpot/StableSpot/assets/66048830/91f03e2f-4797-480b-b46c-9ace2f5f55f6">

아무래도 StableSpot은 체크포인트와 마이그레이션을 지원하기 위해 컨테이너 이미지를 활용하고 있으므로,
DockerSpawner, FargateSpawner, ImageSpawner, KubeSpawner, SystemdSpawner를 살펴보면 좋을 것 같습니다.

SystemdSpawner부터 살펴보도록 하겠습니다.

**Comment by chris0765** [comment]
우선 모든 Custom Spawner들은, Spawner.py의 Spawner class를 상속받아 만들어집니다.
Spawner는 traitlets 라이브러리의 Command 기능을 사용하여, cli를 통해 각각의 기능들(인스턴스 생성, User와 연결, 전체적인 관리 등)을 수행합니다.

더 구체적인 동작 방식을 알아보도록 하겠습니다.

**Comment by hyu-leeky** [comment]
오케이. 그렇다면 우리의 spawner (아마도 podman 기반의 마이그레이션을 지원하는) 를 하나 만든다고 생각하는것도 좋을듯 하네. 김정혁 연구원과 함께 잘 살펴보자.

**Comment by ggamsang** [comment]
chris0765님과 간단히 대화하였습니다. 허브쪽 웹서비스 동작방식 파악 및 커스텀 가능여부파악하기로 했습니다.
웹서버는 tornado라이브러리 사용있는것으로 파악됩니다. 
이를 어떻게 사용하고 있는지 파악하는 것 주가 될 것 같습니다.

**Comment by hyu-leeky** [comment]
오케이 좋습니다. 궁극적으로 우리의 custom 실행 환경을 만들어서 연구실의 노트북 실행 환경을 한번 바꿔 봅시다.

**Comment by chris0765** [comment]
### Spawner의 주요 함수
* start : 서버를 실행하고, 해당 서버의 ip:port를 기록
* poll : 서버의 상태를 지속적으로 모니터링
* stop : 서버를 종료

위 세 함수 모두 traitlets의 Command와 popen을 기반으로 동작하며, 실행될 cli 명령어를 설정 후, popen을 통해 명령어를 실행합니다.
실행될 cli 명령어는 Spawner를 상속한 CustomSpawner class에서 차이가 나타납니다.

### JupyterHub에서 Spawner를 관리하는 방법
하나의 Spawner 코드가 모든 유저의 서버를 관리하지 않습니다.
Spawner는 class로 구현되어있기에, Hub에서 각 유저마다 하나의 Spawner class를 할당합니다.
Hub에 등록된 User/Group 수만큼의 Spawner가 존재하고, 각각의 서버를 각각의 Spawner가 관리합니다.

### JupyterHub의 구조를 StableSpot에 적용하기 위한 변형
저는 우선 JupyterHub의 Hub 부분을 serverless하게 사용하기 위해서, JupyterHub 그 자체가 아닌 구조와 동작 방식만을 사용할 생각이었습니다.
인터넷을 찾아보니 실제로 AWS의 서비스들을 이용하여 serverless하게 JupyterHub와 비슷한 구조를 구현한 케이스가 있었습니다.
https://avishayil.medium.com/serverless-jupyter-hub-with-aws-fargate-and-cdk-2160154187a1

해당 아키텍처를 참고하여 새로운 아키텍처를 설계해보겠습니다.

### 예상되는 문제점
1. Loadbalancer와 멀티클라우드 공존의 문제

위의 아키텍처는 Application Loadbalancer를 활용하여 모든 User가 하나의 Loadbalancer를 사용하도록 설계되어 있습니다.
(Application Loadbalancer의 경우는 {로드밸런서 주소}/{커스텀 depth}와 같은 방식으로 하나의 Loadbalancer URL에 여러 페이지를 사용할 수 있도록 설계되어 있습니다.

그런데 제가 알기로는 타 클라우드 벤더의 인스턴스를 AWS의 로드밸런서에 연결하기 위해서는 Application Loadbalancer가 아닌 Network Loadbalancer를 사용해야 하는 것으로 알고 있고, Network Loadbalancer는 위와 같은 기능을 지원하지 않습니다.

따라서 User마다의 Loadbalancer를 생성해야하는가? 라는 문제가 존재합니다.

2. 인스턴스 자동 종료 기능의 구현 방식

따로 Log Off를 통해 수동으로 Notebook을 백업하고 인스턴스를 종료하는 기능을 추가할 계획이기는 합니다만,
교수님께서 말씀해주신 기능 중 하나인 '일정 시간 Notebook 사용이 없을 경우 인스턴스를 종료'의 구현 방식 설계에 고민이 있습니다.
가장 중요한 것은 어떤 것을 '사용이 없다'의 기준으로 삼아야 하는가입니다.

* running 상태인 Notebook이 없을 때
실제로는 running 상태인 Notebook이 있는 채로 사용이 없는 경우가 많을 것입니다.
(running을 다 stop으로 바꾼다면, 앞서 말씀드린 Log Off를 사용하는 것이 편리하므로 굳이 자동 종료 기능이 필요하지 않습니다.)
때문에 running인 상태인 Notebook이 하나라도 있다면 실제로는 사용이 없음에도 인스턴스가 자동종료되지 않을 수 있습니다.
* CPU/MEM 사용량을 기준으로
MEM 사용량은 Notebook을 사용중이지 않더라도 높게 측정될 수 있습니다.
큰 데이터를 Notebook에서 처리할 때, 데이터를 cell에 올려놓게 된다면, 그 이후로는 실행중인 cell이 없음에도 이미 메모리에 올라와있는 데이터에 의해 높은 MEM 사용량이 측정될 수 있습니다.

**Comment by ggamsang** [comment]
app.py에서 tornado라이브러리를 통해 웹서버가 생성됩니다.
이때 해당 웹서버 서비스들(라우터 ex: /api/...)은 orm.py로 부터 디비에 등록된 서비스들이 생성됩니다.
(좀 더 자세히 파악해보도록 하겠습니다)

위에서 찾아주신 serverless 시도에 대한 링크도 확인해보겠습니다.

**Comment by hyu-leeky** [comment]
오케이. FarGate 를 사용해서 서버리스로 구현을 하는듯 하네. 한번 살펴볼 필요는 있겠다. 실제로 구현을 시도 해봐도 좋을듯 하다. 진행하면서 이야기 나눌 부분있으면 다 같이 이야기해보자.
