### ISSUE TITLE
서버리스 아키텍처를 위한 로드밸런서 대체 방법

### ISSUE THREAD

**Issue by chris0765** [StableSpot/StableSpot#7]
기존 아키텍처에서는, 멀티 클라우드 자원을 활용하기 위해 Network Loadbalancer와 site-to-site VPN을 활용하고 있었습니다.
여기서 Loadbalancer를 사용하는 이유는, Spot Instance의 Public IP가 변경되더라도 사용자는 고정된 URL을 통해 서버에 접속할 수 있도록 하기 위해서입니다.

여기에 추가로 사용자마다 다른 환경을 사용할 수 있도록 시스템 구조를 변경하게 되면서, 하나의 NLB로는 시스템 구성이 불가능한 상태가 되었고, NLB를 대체하기 위한 새로운 아키텍처를 고안해야합니다.

**Comment by chris0765** [comment]
무현님과 이야기를 나눠보았을 때, nginx 등의 프록시 서버를 하나 두고 시스템을 구성하는 것은 어떨까는 이야기가 나왔습니다.

개인적으로는, 어차피 서버를 두게 된다면 프록시 서버가 아니라 JupyterHub의 Hub가 동작하는 서버를 만들고 사용되는 자원 DB를 관리하는 것이 더 좋지 않을까 하는 생각이 들었습니다.

때문에 serverless 상태로 시스템을 구성할 수 있는 방법을 최대한으로 찾아보고, 다른 방법들이 여의치 않다면 어쩔 수 없이 작은 서버를 하나 둬야하지 않을까 싶습니다.

**Comment by chris0765** [comment]
https://lhy.kr/lambda-url-redirection
https://aws.amazon.com/ko/blogs/opensource/sync-routes-across-route-tables-with-aws-sync-routes-a-serverless-open-source-project/
<img width="613" alt="image" src="https://github.com/StableSpot/StableSpot/assets/66048830/3ab18fde-e0d1-4032-87e4-d69c77fb65b1">

API Gateway와 Lambda를 활용한 serverless routing table 구현에 대한 방법들이 몇몇 있는 듯 합니다.
해당 방법을 직접 구성해본 후, StableSpot에 사용할 수 있을지 살펴보도록 하겠습니다.

**Comment by chris0765** [comment]
https://lhy.kr/lambda-url-redirection

해당 URL의 내용을 바탕으로 간단한 시스템을 만들어 보았는데, 제가 기대하던 방식으로 동작하지는 않는 듯 합니다.

* 기대했던(목표하던) 동작

접속된 URL은 변하지 않은 채로 동작
예) www.example.com/user1 접속 시 내용물은 12.34.56.789/tree 이지만, 브라우저 상단의 URL 주소는 계속 www.example.com/user1을 유지

* 실제 동작

URL이 변경됨
예) www.example.com/user1 접속 시 내용물과 브라우저 상단의 URL 주소 모두 12.34.56.789/tree 로 변함

다른 설정들을 통해 목표하던 바를 달성할 수 있을지 조금 더 찾아보겠습니다.

**Comment by chris0765** [comment]
계속해서 찾아봤을 때, 단순히 Lambda측에서의 변경 뿐 아니라, client에서도 URL이 변경되지 않게 하기 위한 javascript 코드를 사용해야 하는 듯 합니다.

간단히 html파일을 하나 만들어 추가 테스트해보겠습니다.

해당 시도에 성공한다면 바로 시스템 아키텍처를 작성할 수 있을 것 같습니다.

**Comment by hyu-leeky** [comment]
재일아 이 기능이 중요하기는 한데, 더 중요하기는 spawner 등을 통해서 노트북 환경을 실행하고 마이그레이션 하고 하는 기능인것 같은데.. 프론트엔드를 서버리스로 만드는건 필요한 기능 중의 하나라고 이야기를 했던거지, 이게 1순위의 일은 아닐것 같거든. 벌써 이것 저것 시도를 해본것 같으니 조금 더 해보기는 하자. 한가지 염두에 둘건 Jupyter Hub 에서 노트북을 시작하게 되어도 이런 식으로 url redirection 등이 필요할지는 잘 생각해봐야겠다. Jupyter Hub 의 동작 방식에 대한 이해가 조금 더 필요해 보이기도 한다.

**Comment by chris0765** [comment]
넵, Spawner 기능 관련해서는 충분히 파악된 것 같아, 서버리스 형태로 서비스를 만들게 된다면 가장 문제가 될 부분이 해당 이슈라 생각해 살펴보고 있었습니다.

## Spawner

* Spawner는 class 객체로 구현되어 한명의 유저가 하나의 Spawner를 가지고 있습니다.
* Spawner는 연결된 User가 사용하는 서버에 대한 것을 총괄합니다.
* 인스턴스의 생성, 생성된 서버의 IP, Port 정보 저장, User의 id에 따른 개인 주피터 서버 URL, 두 정보를 사용한 라우팅, 인스턴스의 종료 등의 기능을 수행합니다.

그리고 위와 같은 Spawner의 기능은 Lambda와 ParameterStore or DynamoDB 등을 사용하는 것으로 구현할 수 있습니다.

## Spawner vs. Lambda(with Parameter Store)

* Spawner는 class 객체로 구현되어 한명의 유저가 하나의 Spawner를 가지고 있습니다.
--> Lambda는 서버리스 서비스이기 때문에, API를 통해 트리거되도록 하여, API에 함수를 호출한 유저의 정보를 넘겨준다면, ParameterStore에서 User의 데이터를 가져와 각각의 유저에 맞게끔 기능할 수 있습니다.
* Spawner는 연결된 User가 사용하는 서버에 대한 것을 총괄합니다.
--> 앞서 말했듯, User의 id등을 Key값에 포함하여 관련 값들을 저장해두면, 추후 Lambda에서 event로 넘겨받은 User의 정보를 사용해 invoke한 User의 서버를 관리할 수 있습니다.
* 인스턴스 생성, 생성된 서버의 IP, Port 정보 저장, User의 id에 따른 개인 ~~~
--> Lambda는 다양한 언어들을 지원하므로, Python을 사용하면 해당 기능들을 모두 구현이 가능합니다.

## 해당 이슈를 우선적으로 진행한 이유

https://avishayil.medium.com/serverless-jupyter-hub-with-aws-fargate-and-cdk-2160154187a1
위에 말한 내용들과, 이 URL을 참고해봤을 때, JupyterHub 자체를 서버리스하게 만드는 것은 금방 할 수 있는 일이라고 생각했습니다. (로그인 부분은 Cognito 활용, 혹은 admin의 관리 기능 등을 추가하기 위해서는 S3 위에서 정적 웹을 서빙하고, 해당 웹에서 Lambda를 Invoke하는 API를 호출)

또한, StableSpot의 핵심 내용이라고 할 수 있는 "라이브 마이그레이션을 통한 Interrupt-Free한 스팟 인스턴스의 사용"을 서버리스 JupyterHub에 어떻게 적용시켜야할까를 생각해봤을 때, 이 부분도 캡스톤때 만들어둔 것들을 활용하면 금방 만들 수 있을 것이라 생각했습니다.

https://github.com/StableSpot/StableSpot/issues/4#issuecomment-1698665739
(위 두 문단에 대한 내용)

위와 같이 생각하고, 아키텍처 설계를 시작해보았는데, 기존의(캡스톤때의) "하나의 인스턴스를 여러 유저가 같이 사용하는 구조"에서 "한명의 유저마다 하나의 서버를 사용하는 구조"로 변경되면서, 기존 시스템을 그대로 적용하는데에 문제가 생겼습니다.

기존 시스템에서, 스팟 인스턴스의 마이그레이션으로 서버의 IP 주소가 달라졌을 때, 사용자가 계속 새롭게 접속할 필요가 없도록 Loadbalancer를 통해 일관된 URL을 제공해왔습니다.
하지만, 각각의 유저가 각각의 서버를 가지게 되면서 유저의 수만큼 Loadbalancer가 필요한 상황이 되어버렸고, 이를 구현하는 것이 불가능한 것은 아니겠지만, 매우 복잡하고 비효율적인 방식으로 보여졌고, 기존의 Loadbalancer의 역할을 대체하기 위한 아키텍처를 설계하고자 했습니다.

이 문제를 해결한다면 아래 과정을 통해 빠르게 시스템을 완성할 수 있을 것이라 생각했습니다.
1. 시스템 아키텍처 설계
2. 세부 알고리즘(KNN, 클라우드 구성 알고리즘 등) 설계
3. 실제 구현

https://github.com/StableSpot/StableSpot/issues/6#issuecomment-1698678209
(Loadbalancer 부분에서 설계가 막힌 내용)

## 추후 진행하고자 하는 이슈

위에서 설명드린대로, Spawner에 대한 이해가 더 필요하다기보다는, 아키텍처를 완성하기 위해 본 이슈를 해결하는게 1순위라고 개인적으로 생각됩니다.
때문에 Fargate 등 다양한 AWS 서비스를 살펴보며 로드밸런서를 대체할 수 있는 시스템을 찾아보고 싶습니다.

**Comment by hyu-leeky** [comment]
재일아 잘 정리했다. 그런데 이정도로 정리가 되었다면 주간 미팅이 있는 월요일이 아니라도 바로 이야기 나누었으면 어땠을까 하는 생각이 들어 ㅎㅎ그렇게 필요할때 바로 이야기 하려고 학교에 나와 있는거고. 빠르게 이야기 나눠야 나도 진행 사항을 알고, 다음 단계 작업도 함께 이야기를 할 수 있으니.

**Comment by chris0765** [comment]
https://github.com/StableSpot/StableSpot/issues/9#issuecomment-1705970714

해당 코멘트 내용대로 아키텍처 설계를 위해 Proxy 구성을 시도하는 이슈입니다.

### 프록시 구현 방안

* 유저마다 각각의 로드밸런서 생성하여 관리
* 작은 프록시 서버 생성
* Route53 DDNS 및 subdomain 기능 활용
* AWS Lambda를 통한 프록시 관리

이 이상의 방법을 생각하기에는 시간적으로도 너무 이슈 하나에 끌리는 느낌도 있어서,
위 방법들이 가능할지 각각 시도해보고, 예상 비용을 비교하여 가장 적합한 방법을 채택하도록 하겠습니다.

**Comment by chris0765** [comment]
# 프록시 구현 방안별 비용 비교

### 유저 수 만큼 로드밸런서 사용

유저 한명당 기본적으로 월 16$ 필요.
트래픽 양에 따라 더 많이 나갈 수 있음

---

### 프록시 서버 생성

온디맨드 t3.large 기준 약 월 60$
트래픽 양에 따른 AutoScaling 사용 시 성능을 만족하며 비용 관리 가능

---

### Route53 subdomain

Route53만 사용한다면 비용은 가장 저렴. 호스팅 존의 레코드가 10000개를 넘지 않는 경우는 Free-tier로 취급 (User 10000명까지 무료 사용 가능)
다만 테스트 당시, TTL을 60초로 설정해두었음에도, 60초를 넘어서 변경된 서버가 반영됨을 확인함.
안정적인 사용을 위해서는 Route53-ELB 구조를 사용해야 하기에 1번과 크게 다르지 않음

---

### AWS Lambda를 통한 서버리스 프록시 서버 구현

해당 방법으로 구현시 거의 완벽한 서버리스 구성이 가능하나, 비용이 매우 많이 드는 방법.
<img width="953" alt="image" src="https://github.com/StableSpot/StableSpot/assets/66048830/813d93dc-dea9-436d-ab2a-49700d41173a">
위 사진에서 각각의 파일이 모두 Lambda를 한번씩 호출함.
각각의 요청은 1초 미만으로 처리가 가능하나, 첫 페이지 로딩만 해도 수십개의 Lambda가 호출이 되며 이후에도 지속적으로 서버와 통신하기 위해 Lambda를 호출함.

---

### 결론

비용만을 생각하면 Route53을 사용한 관리가 가장 좋아보이며, 안정성과 성능을 고려할 경우 ELB 사용이 필수적.
ELB를 통해 추가되는 비용과 스팟 인스턴스를 통해 절감되는 비용이 중요할 듯 합니다.

**Comment by chris0765** [comment]
Route53의 경우 TTL을 10초까지 낮추어 다시 테스트 해봤을 때, 빠르게 변경 내용이 적용되는 것을 확인했습니다.

이 부분은 여러번 반복 테스트를 해보는 것으로 확실하게 파악해보겠습니다.

**Comment by chris0765** [comment]
Route53의 경우 성능과 활용 측면에서는 괜찮으나 보안 접속이 불가능하다는 문제가 존재함.

때문에 쿠버네티스를 적용하여 관리가 가능할 지 시도해볼 계획

쿠버네티스 개념 및 사용 관련해서 학습에 2~3일 정도 소요될 예정

**Comment by chris0765** [comment]
#12 이슈에서 @ggamsang 님께서 이어서 진행
