### ISSUE TITLE
프록시 테스트를 위한 도메인 필요

### ISSUE THREAD

**Issue by chris0765** [StableSpot/StableSpot#8]
프록시 기능을 제대로 테스트해보기 위해 도메인 이름이 필요합니다.
연구실 도메인인 ddps.cloud에, 추후 시스템 완성시 사용하기 위한
jupyter.ddps.cloud 도메인을 미리 생성하고자 합니다.
@kmu-leeky

**Comment by hyu-leeky** [comment]
응 재일아. 필요하면 생성해야지. 그런데 jupyter 보다는 notebook.ddps.cloud 가 맞지 않을까 하는데. prod 계정에 만들수 있을테니 필요하면 생성해서 진행해보자.

**Comment by chris0765** [comment]
넵 notebook.ddps.cloud로 생성하도록 하겠습니다.
